import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root = fileURLToPath(new URL('..', import.meta.url));
const archive = path.join(root, 'dsh-sendfile-0.1.0.tgz');
const recovery = fileURLToPath(new URL('./recovery.py', import.meta.url));
const dshHome = path.join(os.homedir(), '.dsh');
const profile = path.join(dshHome, 'profiles', 'desktop');
const app = '/Applications/DSH Desktop.app';
const kernelRoot = path.join(app, 'Contents/Resources/app.asar.unpacked/node_modules/@deepseek-ai/dsh');
const cli = path.join(kernelRoot, 'lib/bin.js');
console.log('安装计划：完整备份并校验 desktop 插件环境、会话、索引、附件和设置；持久禁用 DragView 并保留安装包；安装候选版。');
if (!process.argv.includes('--apply')) { console.log('仅显示计划。确认并退出 DSH 后运行：node scripts/install.mjs --apply'); process.exit(0); }
if (process.platform !== 'darwin') throw new Error('此安装器仅支持 macOS。');
const stopped = spawnSync('/usr/bin/pgrep', ['-f', '/Applications/DSH Desktop.app/Contents/']);
if (stopped.status === 0) throw new Error('请先退出 DSH Desktop。');
if (stopped.status !== 1) throw new Error('无法检查进程状态，未安装。');
const version = spawnSync('/usr/libexec/PlistBuddy', ['-c', 'Print :CFBundleShortVersionString', path.join(app, 'Contents/Info.plist')], { encoding: 'utf8' }).stdout?.trim();
const kernel = JSON.parse(await fs.readFile(path.join(kernelRoot, 'package.json'), 'utf8')).version;
if (version !== '2.0.4' || kernel !== '0.1.2-alpha.1') throw new Error('DSH 版本与验收基线不同，请先重新验证兼容性。');
await fs.access(archive);
const packageBefore = JSON.parse(await fs.readFile(path.join(profile, 'package.json'), 'utf8'));
if (!packageBefore.dsh?.profile?.bundles?.includes('dsh-dragview')) throw new Error('未发现预期 DragView bundle，需重新核对安装方案。');
const patchFile = path.join(profile, 'cordis.patch.yml');
const originalPatch = await fs.readFile(patchFile, 'utf8');
const activePatch = originalPatch.split('\n').filter(line => !line.trim().startsWith('#')).join('\n').trim();
if (activePatch !== '[]') throw new Error('profile 已有其他覆盖补丁，请人工合并后安装，避免覆盖既有配置。');
const index = process.argv.indexOf('--backup');
let backup = index >= 0 ? process.argv[index + 1] : null;
if (!backup) {
  const result = spawnSync('python3', [recovery, 'backup', '--apply'], { encoding: 'utf8', maxBuffer: 4 * 1024 * 1024 });
  process.stdout.write(result.stdout || ''); process.stderr.write(result.stderr || '');
  if (result.status !== 0) throw new Error('完整备份失败，未安装。');
  backup = JSON.parse(result.stdout.trim().split('\n').at(-1)).backup;
}
const verified = spawnSync('python3', [recovery, 'verify', backup], { stdio: 'inherit' });
if (verified.status !== 0) throw new Error('备份校验未通过，未安装。');
console.log(`完整备份：${backup}`);
const comment = originalPatch.split('\n').filter(line => line.trim().startsWith('#')).join('\n');
const nextPatch = `${comment}\n# dsh-sendfile: keep DragView installed but disabled during acceptance.\n- id: drag-file\n  disabled: true\n`;
const temp = patchFile + `.sendfile-${Date.now()}.tmp`;
await fs.writeFile(temp, nextPatch, { flag: 'wx', mode: 0o600 });
await fs.rename(temp, patchFile);
console.log('DragView 已通过 profile 覆盖层禁用，包和原配置保留。');
const install = spawnSync(process.execPath, [cli, 'plugin', '--profile', 'desktop', 'add', '--ignore-scripts', archive], { env: { ...process.env, DSH_HOME: dshHome }, stdio: 'inherit' });
if (install.status !== 0) throw new Error(`安装失败，请保持 DSH 退出。恢复命令：python3 "${recovery}" restore-profile "${backup}" --apply`);
const next = JSON.parse(await fs.readFile(path.join(profile, 'package.json'), 'utf8'));
if (!next.dependencies?.['dsh-sendfile'] || !next.dsh.profile.bundles.includes('dsh-sendfile') || !next.dependencies?.['dsh-dragview']) throw new Error('依赖或 bundle 核对失败，请保持 DSH 退出并恢复完整插件环境。');
console.log('安装及依赖登记完成。尚需检查有效配置并进行真实桌面验收。');
